### PR TITLE
Option to configure where to run Plugin (admin/site/both)

### PR DESCRIPTION
**Pull request by pe7er**
This PR adds a configuration option where to display the OG Tag form of the Plugin (admin/site/both).

Note that for the configuration filter, I've added some new language strings to the language files that need to be checked.

ccc-socialmedia-param

### CODE REVIEW

**Comment by coolcat-creations** [comment]
Actually the plugin should not run in backend at all because that makes no sense. So I think you mean where the edit form has to be enabled, right?

**Comment by pe7er** [comment]
@coolcat-creations Actually, the ``onContentPrepareForm`` should run in the back-end.
It's to add your OG Tag form to a Joomla Article Edit form.
My PR just gives an option to switch it off in front or back-end.
The website where I use it does not need the OG Tag edit form in the front-end.

**Comment by coolcat-creations** [comment]
Yes then its how you said before. But the field descriptions sound like that the plugin runs in backend / frontend. I mean the execution. Not the Form :-)

**Comment by pe7er** [comment]
@pe7er I updated my PR to make it clear that the configuration option is for the Form display

**Comment by coolcat-creations** [comment]
Merci, I test and merge it asap

**Comment by coolcat-creations** [comment]
Hi @pe7er I tested the plugin but it does not save the selection (tested in Joomla 4.1.4)
Elisa

**Comment by pe7er** [comment]
@coolcat-creations I've created a new PR https://github.com/coolcat-creations/plg_cccsocialmedia/pull/9, so I'm closing this one.

**Pull request closed without merging**
