### PR TITLE
Option to configure where to run Plugin (admin/site/both) v2

### PR DESCRIPTION
**Pull request by pe7er**
This new PR adds a configuration option where to display the OG Tag form of the Plugin (admin/site/both).
(old PR: https://github.com/coolcat-creations/plg_cccsocialmedia/pull/8 )

Note that for the configuration filter, I've added some new language strings to the language files that need to be checked.

Screenshot from 2022-06-16 10-44-27

### CODE REVIEW

**Comment by brianteeman** [comment]
I would look at how this is done in core. A good example would be with the skipto plugin. You also need to make sure it is only running on html ie not on rss feeds and not in modals

**Comment by coolcat-creations** [comment]
@brianteeman this PR is only about where the Form should be displayed not where the plugin has to run. the description is bit misleading and was confusing me as well ;-)
I will test it as soon as possible, thank you @pe7er

**Comment by pe7er** [comment]
@coolcat-creations You're welcome! 
Feel free to improve the label / description and I'll translate it to Dutch.

**Comment by coolcat-creations** [comment]
Thank you @pe7er - I tested it and it works as expected. Merged and will draft a new release very soon. I need to test the plugin display on tag pages. there  seems to be a bug reporte I need to investigate.

**Pull request merged**
